### ISSUE TITLE
TypeError('id parameter must be convertable to int not {0.__class__!r}'.format(id)) from None

### ISSUE THREAD

**Issue by quarkyrobin** [cromachina/fanbox-bot#1]
Hey, I was thrilled to see someone made a fanbox subscription bot and I've been trying to use it, but I've been having some difficulty setting it up. This is the error I've been getting. I'm still pretty new to programming
<img width="860" alt="Screen Shot 2022-06-23 at 8 15 22 PM" src="https://user-images.githubusercontent.com/91914637/175435985-cc9b34de-b4f2-47ee-97e6-d1a827f30a2e.png">
.

**Comment by cromachina** [comment]
This is most likely due to the `config.yml` parser turning config values into either numbers or strings. If you enter just a number, it will be treated as a number. If you enter a number and letters, it will be treated as a string. If you 'quote' the value, it will also be treated as a string, even if it's all numbers.

I can try to fix all of the parts of the config parsing so that you can either put a number or a string and it should convert to the correct type regardless.

To resolve your problem immediately, it looks like parsing is failing when looking at the plan roles, so you need to make sure the plan role in the key position is quoted, like this:

```yml
plan_roles:
  '12345': 98765
```

but **not** like this:

```yml
plan_roles:
  12345: 98765
```

**Comment by cromachina** [comment]
Actually, reading the error more closely, it seems like the role value is a string, but it needs to be a number. In Discord, you need to turn on developer mode and right click on a role to get its ID number.

I will clarify this in the `config-template.yml`.

**Comment by cromachina** [comment]
I pushed 460f645 which contains more clear information about what should go into each field.

**Comment by quarkyrobin** [comment]
I was able to get it working with that clarification. Thank you so much! I am very appreciative that you took the time to make a bot like this.

**Comment by cromachina** [comment]
I'll close this since sufficient documentation seems to suffice for now.
