### ISSUE TITLE
[Error] Body - can't automatically create invite on fanbox

### ISSUE THREAD

**Issue by ron3dhj** [cromachina/fanbox-bot#3]
![gambar](https://user-images.githubusercontent.com/109651844/182536434-f9ce945b-9339-41f9-a59c-b14cb02474ec.png)

**Comment by cromachina** [comment]
It seems like there was an error when contacting the Fanbox API. Every now and then this happens randomly, maybe because of issues on the Fanbox server.

To eliminate errors with your configuration, can you try running the invite creation manually by messaging the bot `!regen-invite`.
- The config value `admin_id` needs to be set for the bot to accept this command.
- The config value `fanbox_discord_post_id` needs to be set correctly. I'm assuming this is working because you were able to retrieve the post before modifying it.

It may be possible that it's one of the unknown fields for the Fanbox post update that I had to copy which is causing an error (I'm not sure if it's unique per user or not, nor how to retrieve it programmatically).

**Comment by cromachina** [comment]
I will also try to add some error catching at the Fanbox call so that the error print out will be more informative.

**Comment by cromachina** [comment]
I added the error checking in 21ef099. However, Fanbox typically responds with `{error: "general"}`, and nothing actually useful, like why there was an error. At least now we will be sure if Fanbox is rejecting the request for any reason.

**Comment by cromachina** [comment]
I accidentally pushed a bug, just fixed it in 7b22fee
